#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// initialize ip header
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	// fprintf(stderr, "TODO: longest prefix match for the packet.\n");

	rt_entry_t *rt_entry, *lpm_entry = NULL;
	u32 max_mask = 0;
	list_for_each_entry(rt_entry, &rtable, list)
	{
		if ((dst & rt_entry->mask) == (rt_entry->dest & rt_entry->mask))
		{
			if (rt_entry->mask > max_mask)
			{
				max_mask = rt_entry->mask;
				lpm_entry = rt_entry;
			}
		}
	}
	return lpm_entry;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	// fprintf(stderr, "TODO: send ip packet.\n");

	struct ether_header *eth_hdr = (void *)packet;
	struct iphdr *ip_hdr = packet_to_ip_hdr(packet);

	// search routing table
	u32 daddr = ntohl(ip_hdr->daddr);
	rt_entry_t *rt_entry = longest_prefix_match(daddr);

	// no match entry -> drop the packet
	if (!rt_entry)
	{
		free(packet);
		return;
	}

	// next hop: gate way(differnet LAN) or daddr(same LAN)
	u32 next_hop = rt_entry->gw ? rt_entry->gw : daddr;

	iface_send_packet_by_arp(rt_entry->iface, next_hop, packet, len);
}

// forward IP datagram
void ip_forward_packet(char *packet, int len)
{
	// parse packet
	struct iphdr *ip_hdr = packet_to_ip_hdr(packet);
	u32 daddr = ntohl(ip_hdr->daddr);

	// TTL
	if (--ip_hdr->ttl == 0)
	{
		icmp_send_packet(packet, len, ICMP_TIME_EXCEEDED, ICMP_EXC_TTL);
		free(packet);
		return;
	}

	// recalculate checksum
	ip_hdr->checksum = ip_checksum(ip_hdr);

	// search routing table
	rt_entry_t *rt_entry = longest_prefix_match(daddr);
	if (!rt_entry)
	{
		// what code exactly is here ???
		icmp_send_packet(packet, len, ICMP_DEST_UNREACH, ICMP_NET_UNREACH);
		free(packet);
		return;
	}

	// If the packet is ICMP echo request and the destination IP address is equal to
	// the IP address of the iface, send ICMP echo reply;
	// dst is self
	if (daddr == rt_entry->iface->ip)
	{
		switch (ip_hdr->protocol)
		{
		case IPPROTO_ICMP:
			struct icmphdr *icmp_hdr = (void *)IP_DATA(ip_hdr);
			if (icmp_hdr->type == ICMP_ECHOREQUEST)
				icmp_send_packet(packet, len, ICMP_ECHOREPLY, 0);
			free(packet);
			break;
		default:
			free(packet);
			break;
		}
		return;
	}

	// next hop
	u32 next_hop = rt_entry->gw ? rt_entry->gw : daddr;

	// forward packet
	iface_send_packet_by_arp(rt_entry->iface, next_hop, packet, len);
}